pipeline {
    agent any
    
    tools {
        maven 'maven-3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nourhanosma47/iVolve-training.git'
            }
        }

        stage('Build Maven') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Docker Build & Push') {
            steps {
                // هنا بنستخدم الأوامر مباشرة بدل الـ tool
                sh 'docker build -t nourhanosma47/jenkins-app:${BUILD_NUMBER} .'
                withCredentials([usernamePassword(credentialsId: 'docker-hub-id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                    sh 'docker push nourhanosma47/jenkins-app:${BUILD_NUMBER}'
                }
            }
        }
    }
}
