pipeline {
    agent any
    
    tools {
        maven 'maven-3'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nourhanosma47/iVolve-training.git'
            }
        }

        stage('Build & Push Image (using Jib)') {
            steps {
                // بننادي الـ credentials بتاعة Docker Hub
                withCredentials([usernamePassword(credentialsId: 'dockerhub-id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    // السطر اللي جاي ده هو اللي كان ناقص عشان يدخل الفولدر اللي فيه الكود
                    dir('argocd') { 
                        script {
                            // بناء الصورة ورفعها مباشرة برقم الـ Build الحالي
                            sh "mvn compile jib:build -Dimage=docker.io/nourhanosma47/jenkins-app:${BUILD_NUMBER}"
                        }
                    }
                }
            }
        }
        
        stage('Update Manifest') {
            steps {
                dir('argocd') {
                    withCredentials([usernamePassword(credentialsId: 'github-token-secret', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh """
                            # تعديل رقم الصورة في ملف الـ deployment ليطابق الصورة المرفوعة
                            sed -i "s|image:.*|image: nourhanosma47/jenkins-app:${BUILD_NUMBER}|g" deployment.yaml
                            
                            # إعدادات جيت للرفع
                            git config user.email "nourhan@example.com"
                            git config user.name "Nourhan"
                            
                            git add deployment.yaml
                            git commit -m "Update image to version ${BUILD_NUMBER} [skip ci]"
                            
                            # الرفع لـ GitHub عشان ArgoCD يسحب التغيير
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/nourhanosma47/iVolve-training.git main
                        """
                    }
                }
            }
        }
    }
}
